blueprint:
  name: View Assist - What's the Weather - LLM Script
  source_url: https://github.com/relust/View-Assist-ro-support/blob/main/LLM%20Scripts/how%60s_the_weather-llm_script.yaml
  description: >
    This blueprint creates a script to navigate the last active View Assist satellite
    to a weather dashboard view.

    When weather information is requested, the LLM MUST do two things:

    1. Retrieve and verbally provide all weather information (temperature, wind, humidity, etc.)
       using the user's weather entity, formatting the data explicitly for TTS
       (for example, "-5.5 °C" should be spoken as "minus five point five degrees").
    2. Execute this script to navigate the last active View Assist satellite to 
       the weather dashboard view.

    This script ONLY updates the visual interface and does NOT generate spoken responses.
  domain: script
  author: Relu

  homeassistant:
    min_version: 2024.6.0

  input:
    view_path:
      name: Weather view path
      description: >
        Dashboard view path that should be opened when the user asks
        about the weather.
      default: /view-assist/weather
      selector:
        text:

    last_satellite_input_text:
      name: Last active satellite input_text
      description: >
        input_text entity that stores the device_id of the last active
        View Assist satellite.
      default: input_text.last_used_satellite_device_id
      selector:
        entity:
          domain: input_text

    llm_description:
      name: LLM Description
      description: >
        Default description to be used by the LLM when this script is run.
        You can edit it if needed.
      default: >
        This script is intended to be used by an LLM when the user asks for
        weather information.

        When weather information is requested, the LLM MUST do two things:

        1. Retrieve and verbally provide all weather information (temperature, wind, humidity, etc.)
           using the user's weather entity (for example: weather.openweathermap), formatting the data explicitly for TTS
           (for example, "-5.5 °C" should be spoken as "minus five point five degrees").		   

        2. Execute this script to navigate the last active View Assist
           satellite to the weather dashboard view.

        This script is responsible ONLY for updating the visual interface.
        It does NOT return weather data and does NOT generate spoken responses.
        The LLM must always provide the spoken weather response itself.
      selector:
        text:

mode: single
max_exceeded: silent
fields:
  llm_description_field:
    selector:
      text: null
    name: LLM Description
    description: !input llm_description
    required: false

sequence:
  - variables:
      last_satellite_entity: !input last_satellite_input_text
      view_var: !input view_path
      target_satellite_device: >-
        {{ view_assist_entity(states(last_satellite_entity)) }}
      llm_description_var: !input llm_description

  - alias: Navigate View Assist satellite to weather view
    action: view_assist.navigate
    data:
      device: "{{ target_satellite_device }}"
      path: "{{ view_var }}"
