blueprint:
  name: View Assist - Alarms Reminders Timers - LLM Script
  domain: script
  author: Relu Stoleru
  description: >
    Script helper for controlling View Assist alarms, timers, and reminders.
    Can be called by an LLM or manually from Developer Tools.

    REQUIREMENTS:
    - [View Assist integration](https://github.com/dinki/view_assist_integration)
    - Recommended: [View Assist Companion App](https://github.com/msp1974/ViewAssist_Companion_App)
    - input_text helper to store the last active satellite
    - Automation to update last active satellite:
      [Set Last Active Satellite Blueprint](https://github.com/relust/View-Assist-ro-support/blob/main/LLM_scripts/blueprint-set_last_active_satellite.yaml)

  homeassistant:
    min_version: 2024.6.0

  input:
    last_satellite_input_text:
      name: Last active satellite input_text
      description: >
        input_text helper that stores the device_id of the last active
        View Assist satellite.
      default: input_text.last_used_satellite_device_id
      selector:
        entity:
          domain: input_text

    view_path:
      name: Alarm view path
      description: >
        Dashboard view path shown when alarms, timers or reminders are displayed.
      default: /view-assist/alarm
      selector:
        text:

    alarm_sound_path:
      name: Alarm sound path
      description: >
        Media file played when an alarm or timer expires.
      default: /view_assist/views/alarm/sounds_timer_finished.wav
      selector:
        text:

    default_snooze_minutes:
      name: Default snooze time (minutes)
      description: >
        Snooze duration used if snooze_minutes is not provided.
      default: 10
      selector:
        number:
          min: 1
          max: 120

mode: parallel
max_exceeded: silent

fields:

  action_type:
    name: Action
    description: >
      Script for setting alarms, reminders, and timers using View Assist.
      Select ONE action below and complete only the fields required for that action.

      • set_timer  
        Used for: "set a timer for 5 minutes", "set an alarm for 6:00", "remind me tomorrow at 7 to call John"  
        Required: timer_type, time  
        Optional: name

      • list_timers  
        Used for: "list my timers", "list my alarms", "list my reminders"  
        No additional fields required

      • show_ui  
        Used for: "show my timers", "show my alarms", "show my reminders"  
        No additional fields required

      • timer_remaining  
        Used for: "how much time is left on my timer", "how much time is left on my kitchen timer"  
        Optional: name

      • snooze_timer  
        Used for: "snooze my alarm", "snooze the timer"  
        Required: timer_id  
        Optional: snooze_minutes (defaults to configured value)

      • cancel_timer  
        Used for: "cancel my alarm", "stop the timer"  
        Required: timer_id

      • alarm_ringing  
        Internal use only: plays alarm sound and shows UI

      • dismiss_alarm  
        Used for: "stop the alarm", "dismiss the alarm"  
        Required: timer_id

      Spoken responses must always be generated by the LLM.
    selector:
      select:
        multiple: false
        options:
          - set_timer
          - cancel_timer
          - list_timers
          - timer_remaining
          - snooze_timer
          - alarm_ringing
          - dismiss_alarm
          - show_ui
    required: true

  timer_type:
    name: Timer type
    description: >
      Required only for set_timer.
    selector:
      select:
        options:
          - timer
          - alarm
          - reminder
    required: false

  time:
    name: Time
    description: >
      Time expression used when creating timers, alarms or reminders.
    selector:
      text:
    required: false

  name:
    name: Name
    description: >
      Optional name for a timer, alarm or reminder.
    selector:
      text:
    required: false

  timer_id:
    name: Timer ID
    description: >
      Required when snoozing, canceling or dismissing an existing timer or alarm.
    selector:
      text:
    required: false

  snooze_minutes:
    name: Snooze time (minutes)
    description: >
      Optional. Defaults to the configured snooze time.
    selector:
      number:
        min: 1
        max: 120
    required: false

sequence:
  - variables:
      last_satellite_entity: !input last_satellite_input_text
      satellite_entity: "{{ view_assist_entity(states(last_satellite_entity)) }}"
      media_player: "{{ state_attr(satellite_entity, 'mediaplayer_device') }}"
      view: !input view_path
      alarm_sound: !input alarm_sound_path
      default_snooze: !input default_snooze_minutes
      snooze_time: "{{ snooze_minutes | default(default_snooze) }}"

  - choose:

      - conditions: "{{ action_type == 'set_timer' }}"
        sequence:
          - action: view_assist.set_timer
            data:
              device_id: "{{ states(last_satellite_entity) }}"
              type: "{{ timer_type }}"
              time: "{{ time }}"
              name: "{{ name | default('') }}"
          - action: view_assist.navigate
            data:
              device: "{{ satellite_entity }}"
              path: "{{ view }}"

      - conditions: "{{ action_type == 'alarm_ringing' }}"
        sequence:
          - action: view_assist.set_state
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              mode: hold
          - action: view_assist.sound_alarm
            data:
              entity_id: "{{ media_player }}"
              media_file: "{{ alarm_sound }}"
          - action: view_assist.navigate
            data:
              device: "{{ satellite_entity }}"
              path: "{{ view }}"

      - conditions: "{{ action_type == 'dismiss_alarm' }}"
        sequence:
          - action: view_assist.cancel_sound_alarm
            data:
              entity_id: "{{ media_player }}"
          - action: view_assist.cancel_timer
            data:
              timer_id: "{{ timer_id }}"
          - action: view_assist.set_state
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              mode: normal

      - conditions: "{{ action_type == 'snooze_timer' }}"
        sequence:
          - action: view_assist.cancel_sound_alarm
            data:
              entity_id: "{{ media_player }}"
          - action: view_assist.snooze_timer
            data:
              timer_id: "{{ timer_id }}"
              time: "{{ snooze_time }} minutes"
          - action: view_assist.set_state
            target:
              entity_id: "{{ satellite_entity }}"
            data:
              mode: normal

      - conditions: "{{ action_type == 'cancel_timer' }}"
        sequence:
          - action: view_assist.cancel_sound_alarm
            data:
              entity_id: "{{ media_player }}"
          - action: view_assist.cancel_timer
            data:
              timer_id: "{{ timer_id }}"

      - conditions: "{{ action_type in ['list_timers', 'show_ui', 'timer_remaining'] }}"
        sequence:
          - action: view_assist.navigate
            data:
              device: "{{ satellite_entity }}"
              path: "{{ view }}"
